#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Disable concurent to run `check-types` after ESLint in lint-staged
npx lint-staged --concurrent false
# Sync possible .env changes to .env.example
# pnpm exec run-s env

# Sync env file with types
